meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-120000
  update_watch_time: 1000-60000
  serial: false

jobs:
  - name: docker_server_z1
    template: docker_server
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))

networks: (( merge ))

properties: {}
